version: '3.8'

services:
  kim-loan-chemicals:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    restart: unless-stopped
    container_name: kim-loan-chemicals-website
    
  # Optional: Add Nginx reverse proxy for production
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      # Uncomment for SSL certificates
      # - ./certs:/etc/nginx/certs:ro
    depends_on:
      - kim-loan-chemicals
    restart: unless-stopped
    container_name: kim-loan-chemicals-nginx
    profiles:
      - production