version: '3.8'

services:
  kim-loan-chemicals:
    image: kim-loan-chemicals:latest
    container_name: kim-loan-chemicals-website
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - NEXT_TELEMETRY_DISABLED=1
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - kim-loan-network

  # Nginx reverse proxy for production
  nginx:
    image: nginx:alpine
    container_name: kim-loan-chemicals-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.prod.conf:/etc/nginx/nginx.conf:ro
      - ./ssl-certs:/etc/nginx/certs:ro
      - ./logs/nginx:/var/log/nginx
    depends_on:
      kim-loan-chemicals:
        condition: service_healthy
    networks:
      - kim-loan-network
    profiles:
      - production

  # Optional: Watchtower for automatic updates
  watchtower:
    image: containrrr/watchtower
    container_name: kim-loan-chemicals-watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_POLL_INTERVAL=86400  # Check daily
      - WATCHTOWER_INCLUDE_STOPPED=true
    command: kim-loan-chemicals-website
    profiles:
      - autoupdate

networks:
  kim-loan-network:
    driver: bridge